// Real app definitions — seeds into Project + ProjectTool entities on first run
export const TERRELLOS_APPS = [
  {
    slug: 'pastor-ai',
    name: 'TerrellOS',
    description: 'AI-powered church platform with sermon prep, Bible study generation, member management, and prayer requests.',
    emoji: '✝️',
    domain: 'pastorai.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, Supabase',
    status: 'building',
    tools: [
      { name: 'Bible Study Generator', slug: 'bible-study', icon_emoji: '📖', status: 'active', route: '/tools/bible-engine' },
      { name: 'Sermon Prep', slug: 'sermon-prep', icon_emoji: '🎙️', status: 'planned', route: '/tools/sermon-prep' },
      { name: 'Church Dashboard', slug: 'church-dashboard', icon_emoji: '⛪', status: 'planned', route: '/tools/church-dashboard' },
      { name: 'Member Management', slug: 'members', icon_emoji: '👥', status: 'planned', route: '/tools/members' },
      { name: 'Prayer Requests', slug: 'prayer', icon_emoji: '🙏', status: 'planned', route: '/tools/prayer' },
      { name: 'Admin Dashboard', slug: 'admin', icon_emoji: '🛡️', status: 'planned', route: '/admin' },
      { name: 'System Logs', slug: 'logs', icon_emoji: '📋', status: 'active', route: '/live-logs' },
      { name: 'Domain Settings', slug: 'domain', icon_emoji: '🌐', status: 'planned', route: '/settings' },
      { name: 'AI Model Settings', slug: 'ai-settings', icon_emoji: '🤖', status: 'planned', route: '/settings' },
      { name: 'Code/Config View', slug: 'code-config', icon_emoji: '⚙️', status: 'active', route: '/backend-manifest' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'eternal-echoes',
    name: 'TerrellOS',
    description: 'AI memorial platform with voice cloning, companion AI, and scheduled messages for loved ones.',
    emoji: '🕊️',
    domain: 'eternalechoes.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, ElevenLabs, OpenAI, Supabase',
    status: 'building',
    tools: [
      { name: 'Memorial Profiles', slug: 'memorial-profiles', icon_emoji: '🌹', status: 'planned', route: '/tools/memorial-profiles' },
      { name: 'Voice Survey', slug: 'voice-survey', icon_emoji: '🎤', status: 'active', route: '/tools/voice-lab' },
      { name: 'AI Companion', slug: 'ai-companion', icon_emoji: '💬', status: 'active', route: '/tools/chat-engine' },
      { name: 'Voice Clone Settings', slug: 'voice-clone', icon_emoji: '🔊', status: 'active', route: '/tools/voice-lab' },
      { name: 'Secret Vault', slug: 'secret-vault', icon_emoji: '🔒', status: 'active', route: '/tools/memory-vault' },
      { name: 'Message Scheduler', slug: 'message-scheduler', icon_emoji: '📅', status: 'planned', route: '/admin/automation' },
      { name: 'Admin Dashboard', slug: 'admin', icon_emoji: '🛡️', status: 'active', route: '/admin' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'kindred-love-birds',
    name: 'Kindred Love Birds',
    description: 'AI-powered matchmaking platform with compatibility analysis, conversation prompts, and relationship coaching.',
    emoji: '💑',
    domain: 'kindredlovebirds.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, Supabase',
    status: 'building',
    tools: [
      { name: 'Match Engine', slug: 'match-engine', icon_emoji: '💘', status: 'planned', route: '/tools/match-engine' },
      { name: 'AI Compatibility', slug: 'compatibility', icon_emoji: '🧠', status: 'planned', route: '/tools/compatibility' },
      { name: 'Conversation Prompts', slug: 'prompts', icon_emoji: '💬', status: 'planned', route: '/tools/chat-engine' },
      { name: 'Relationship Coach', slug: 'coach', icon_emoji: '❤️', status: 'planned', route: '/tools/coach' },
      { name: 'Profiles', slug: 'profiles', icon_emoji: '👤', status: 'planned', route: '/tools/profiles' },
      { name: 'Admin Dashboard', slug: 'admin', icon_emoji: '🛡️', status: 'planned', route: '/admin' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'residentsync',
    name: 'ResidentSync AI',
    description: 'Property management AI with resident communication, maintenance requests, and lease automation.',
    emoji: '🏢',
    domain: 'residentsync.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, Supabase',
    status: 'building',
    tools: [
      { name: 'Resident Portal', slug: 'resident-portal', icon_emoji: '🏠', status: 'planned', route: '/tools/resident-portal' },
      { name: 'Maintenance Requests', slug: 'maintenance', icon_emoji: '🔧', status: 'planned', route: '/tools/maintenance' },
      { name: 'Lease Manager', slug: 'lease', icon_emoji: '📄', status: 'planned', route: '/tools/lease' },
      { name: 'AI Communication', slug: 'ai-comms', icon_emoji: '💬', status: 'planned', route: '/tools/chat-engine' },
      { name: 'Payment Tracking', slug: 'payments', icon_emoji: '💳', status: 'planned', route: '/tools/payments' },
      { name: 'Admin Dashboard', slug: 'admin', icon_emoji: '🛡️', status: 'planned', route: '/admin' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'all-around-customs',
    name: 'All Around Customs / AI Print Shop',
    description: 'AI-powered custom print shop with DTF gang sheet builder, product builder, and automated order management.',
    emoji: '🎨',
    domain: 'allaroundcustoms.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, Supabase, Wix Payments',
    status: 'building',
    tools: [
      { name: 'Product Builder', slug: 'product-builder', icon_emoji: '👕', status: 'active', route: '/tools/product-builder' },
      { name: 'DTF Gang Sheet Builder', slug: 'gang-sheet', icon_emoji: '🖨️', status: 'building', route: '/tools/gang-sheet' },
      { name: 'Uploads', slug: 'uploads', icon_emoji: '📤', status: 'active', route: '/upload-vault' },
      { name: 'Orders', slug: 'orders', icon_emoji: '📦', status: 'planned', route: '/tools/orders' },
      { name: 'Pricing', slug: 'pricing', icon_emoji: '💰', status: 'planned', route: '/pricing' },
      { name: 'Wix Payments', slug: 'wix-payments', icon_emoji: '💳', status: 'building', route: '/billing' },
      { name: 'Admin Queue', slug: 'admin-queue', icon_emoji: '📋', status: 'planned', route: '/admin' },
      { name: 'AI Design Assistant', slug: 'ai-design', icon_emoji: '🤖', status: 'active', route: '/tools/avatar-lab' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'wix_payments', name: 'Wix Payments', env_key_name: 'WIX_PAYMENTS_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'tmg-torque',
    name: 'TMG Torque Master Garage',
    description: 'Automotive AI with diagnostic tools, service scheduling, inventory tracking, and customer management.',
    emoji: '🔧',
    domain: 'tmgtorque.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, Supabase',
    status: 'building',
    tools: [
      { name: 'Vehicle Diagnostics', slug: 'diagnostics', icon_emoji: '🚗', status: 'planned', route: '/diagnostics' },
      { name: 'Service Scheduler', slug: 'scheduler', icon_emoji: '📅', status: 'planned', route: '/tools/scheduler' },
      { name: 'Inventory', slug: 'inventory', icon_emoji: '📦', status: 'planned', route: '/tools/inventory' },
      { name: 'Customer Management', slug: 'customers', icon_emoji: '👥', status: 'planned', route: '/tools/customers' },
      { name: 'Work Orders', slug: 'work-orders', icon_emoji: '🔩', status: 'planned', route: '/tools/work-orders' },
      { name: 'AI Advisor', slug: 'ai-advisor', icon_emoji: '🤖', status: 'planned', route: '/tools/chat-engine' },
      { name: 'Admin Dashboard', slug: 'admin', icon_emoji: '🛡️', status: 'planned', route: '/admin' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
    ],
  },
  {
    slug: 'builders-ai',
    name: "Builder's AI Assistant",
    description: 'Universal AI coding assistant with code generation, debugging, deployment, and project scaffolding tools.',
    emoji: '🏗️',
    domain: 'buildersai.terrell.app',
    live_url: '',
    backend_url: 'https://terrellos-backend.fly.dev',
    framework: 'React + FastAPI',
    tech_stack: 'React, Python, OpenAI, GitHub API, Supabase',
    status: 'active',
    tools: [
      { name: 'AI Builder', slug: 'ai-builder', icon_emoji: '⚡', status: 'active', route: '/ai-builder' },
      { name: 'Code Executor', slug: 'code-exec', icon_emoji: '💻', status: 'active', route: '/tools/ai-builder' },
      { name: 'Project Scaffolder', slug: 'scaffolder', icon_emoji: '📐', status: 'active', route: '/projects' },
      { name: 'Deploy Manager', slug: 'deploy', icon_emoji: '🚀', status: 'active', route: '/tools/deploy' },
      { name: 'Debug Console', slug: 'debug', icon_emoji: '🐛', status: 'active', route: '/admin/live-console' },
      { name: 'Build Logs', slug: 'logs', icon_emoji: '📋', status: 'active', route: '/build-logs' },
      { name: 'Workflow Builder', slug: 'workflow', icon_emoji: '🔗', status: 'active', route: '/workflow-builder' },
    ],
    integrations: [
      { provider: 'openai', name: 'OpenAI GPT-4', env_key_name: 'OPENAI_API_KEY', status: 'connected' },
      { provider: 'supabase', name: 'Supabase DB', env_key_name: 'SUPABASE_URL', status: 'connected' },
      { provider: 'github', name: 'GitHub API', env_key_name: 'GITHUB_TOKEN', status: 'pending' },
    ],
  },
];